# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azbrowse < Formula
  desc "An interactive CLI for browsing Azure, inspired by http://resources.azure.com/"
  homepage "https://github.com/lawrencegripper/azbrowse"
  version "2.1.673"

  on_macos do
    url "https://github.com/lawrencegripper/azbrowse/releases/download/v2.1.673/azbrowse_darwin_amd64.tar.gz"
    sha256 "dd62909300e22f019928433392ceb5fcdaa37c58d49b7374aea2d11074ea6c83"

    def install
      bin.install "azbrowse"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Azbrowse
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lawrencegripper/azbrowse/releases/download/v2.1.673/azbrowse_linux_amd64.tar.gz"
      sha256 "4567b4d5d4500b39ca5aa733dbe665dd7fa08e5477c6c7ceaa27ad652894fa98"

      def install
        bin.install "azbrowse"
      end
    end
  end

  test do
    system "#{bin}/azbrowse --version"
  end
end
